website/views.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func
from .expense import db
from .models import Expense, Income

views = Blueprint('views', __name__)
today = datetime.now().date()


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        typeofexpense = request.form.get('typeOfExpense')
        amount = request.form.get('amount')
        category = request.form.get('category')
        desc = request.form.get('description')

        if not typeofexpense:
            flash("Please select the type of expense!", category='error')
        elif not amount:
            flash("Please enter the amount!", category='error')
        elif not category:
            flash("Please select the category!", category='error')
        elif not desc:
            flash("Please enter the description!", category='error')
        else:
            if typeofexpense == 'expense':
                new_expense = Expense(
                    name=desc, category=category, amount=amount, user_id=current_user.id, date=datetime.utcnow())
                db.session.add(new_expense)
                db.session.commit()
                flash("Expense added!", category='success')
            elif typeofexpense == 'income':
                new_income = Income(
                    name=desc, category=category, amount=amount, user_id=current_user.id, date=datetime.utcnow())
                db.session.add(new_income)
                db.session.commit()
                flash("Income added!", category='success')

    return render_template("home.html", user=current_user)


@views.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    expenses = Expense.query.filter_by(
        user_id=current_user.id).order_by(Expense.date.desc()).all()
    incomes = Income.query.filter_by(
        user_id=current_user.id).filter(func.date(Income.date)).order_by(Income.date.desc()).all()
    total_expense = db.session.query(func.sum(Expense.amount)).filter_by(
        user_id=current_user.id).scalar()
    total_income = db.session.query(func.sum(Income.amount)).filter_by(
        user_id=current_user.id).scalar()
    expense_dates = db.session.query(func.date(Expense.date).label(
        'date')).filter_by(user_id=current_user.id).distinct().all()
    income_dates = db.session.query(func.date(Income.date).label(
        'date')).filter_by(user_id=current_user.id).distinct().all()
    expenses_by_date = db.session.query(
        func.date(Expense.date).label('date'),  # Extract date (without time)
    ).filter_by(user_id=current_user.id) \
        .group_by(func.date(Expense.date)) \
        .order_by(func.date(Expense.date).desc()) \
        .all()
    return render_template("profile.html", user=current_user, expenses=expenses, incomes=incomes, total_expense=total_expense, total_income=total_income, expense_dates=expense_dates, income_dates=income_dates)


@views.route("/delete-expense/<int:id>", methods=['POST'])
@login_required
def delete_expense(id):
    expense = Expense.query.get_or_404(id)

    # Optional: Ensure only the owner can delete their expense
    if expense.user_id != current_user.id:
        flash("You don't have permission to delete this expense.", category='error')
        return redirect(url_for('views.profile'))

    db.session.delete(expense)
    db.session.commit()
    flash('Expense deleted!', category='success')
    return redirect(url_for('views.profile'))


@views.route("/delete-income/<int:id>", methods=['POST'])
@login_required
def delete_income(id):
    income = Income.query.get_or_404(id)

    # Optional: Ensure only the owner can delete their expense
    if income.user_id != current_user.id:
        flash("You don't have permission to delete this expense.", category='error')
        return redirect(url_for('views.profile'))

    db.session.delete(income)
    db.session.commit()
    flash('Income deleted!', category='success')
    return redirect(url_for('views.profile'))


@views.route("/update-expense/<int:id>", methods=['GET', 'POST'])
@login_required
def update_expense(id):
    expense = Expense.query.get_or_404(id)

    # Optional: Ensure only the owner can update their expense
    if expense.user_id != current_user.id:
        flash("You don't have permission to update this expense.", category='error')
        return redirect(url_for('views.profile'))

    if request.method == 'POST':
        expense.name = request.form.get('name')
        expense.category = request.form.get('category')
        expense.amount = request.form.get('amount')
        db.session.commit()
        flash('Expense updated!', category='success')
        return redirect(url_for('views.profile'))

    return render_template('update_expense.html', expense=expense)


@views.route("/update-income/<int:id>", methods=['GET', 'POST'])
@login_required
def update_income(id):
    income = Income.query.get_or_404(id)

    # Optional: Ensure only the owner can update their income
    if income.user_id != current_user.id:
        flash("You don't have permission to update this income.", category='error')
        return redirect(url_for('views.profile'))

    if request.method == 'POST':
        income.name = request.form.get('name')
        income.category = request.form.get('category')
        income.amount = request.form.get('amount')
        db.session.commit()
        flash('Income updated!', category='success')
        return redirect(url_for('views.profile'))

    return render_template('update_income.html', income=income)

website/templates/home.html
{% extends "index.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<h1>Expense Tracker</h1>
<form method="POST">

    <div class="form-group mt-3">
        <label for="typeOfExpense">Expense or Income</label>
        <div class="row">
            <div class="col-auto">
                <input type="radio" id="expense" name="typeOfExpense" value="expense">
                <label for="expense">Expense</label>
            </div>
            <div class="col-auto">
                <input type="radio" id="income" name="typeOfExpense" value="income">
                <label for="income">Income</label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="amount">Amount</label>
        <input type="number" class="form-control" id="amount" name="amount" placeholder="Enter the amount">
    </div>
    <div class="form-group">
        <label for="category">Category</label>
        <input type="text" class="form-control" id="category" name="category" placeholder="Enter the category">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <input type="text" class="form-control" id="description" name="description" placeholder="Enter the description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />

    <title>{%block title%} Home {% endblock %}</title>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a href="/profile" class="nav-item nav-link" id="profile">Welcome, {{ user.username }}!</a>
                <a href="/" class="nav-item nav-link" id="home">Expense Tracker</a>
                <a href="/login" class="nav-item nav-link" id="login">Login</a>
                <a href="/logout" class="nav-item nav-link" id="logout">Logout</a>
                {% else %}
                <a href="/sign-up" class="nav-item nav-link" id="sign-up">Sign Up</a>
                <a href="/" class="nav-item nav-link" id="home">Home</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">{%block content %} {% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

website/templates/login.html
{% extends "index.html" %}
{% block title %} Login {% endblock %}
{% block content %}
<form method="POST">
    <h3 class="text-center">Log In</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/profile.html
{% extends "index.html" %}
{% block title %} My Profile {% endblock %}
{% block content %}
<h1 class="mt-2 mb-3">My Income and Expenses - <span class="text-info">₱{{total_income - total_expense}}</span></h1>
<div class="row mb-3">
    <h3 class="col-auto" id="title-header">Expenses - <span class="text-danger">₱{{total_expense}}</span></h3>
    <button class="col-auto btn-success ml-auto" onclick="showTable('incomes')">Show Income</button>
    <button class="col-auto btn btn-danger ml-2" onclick="showTable('expenses')">Show Expenses</button>
</div>
<div class="row mb-3">
    <div class="col-auto">
        <label for="date-filter">Filter by Date:</label>
        <select id="date-filter" class="form-control" onchange="filterExpensesByDate()">
            <option value="">All Dates</option>
            {% for date in expense_dates %}
            <option value="{{ date.date }}">{{ date.date }}</option>
            {% endfor %}
        </select>
    </div>
</div>
<table class="table table-striped table-bordered table-hover" id="expenses-table">
    <thead class="table-dark">
        <tr>
            <th>Category</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="expenses-tbody">
        {% for expense in expenses %}
        <tr data-date="{{ expense.date }}">
            <td>{{ expense.category }}</td>
            <td>{{ expense.name }}</td>
            <td>{{ "%.2f"|format(expense.amount) }}</td>
            <td>{{ expense.date }}</td>
            <td>
                <a href="{{ url_for('views.update_expense', id=expense.id) }}" class="btn btn-warning btn-sm">Update</a>
                <form action="{{ url_for('views.delete_expense', id=expense.id) }}" method="POST"
                    style="display:inline;">
                    <button type="submit" class="btn btn-danger btn-sm"
                        onclick="return confirm('Are you sure you want to delete this expense?')">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<table class="table table-striped table-bordered table-hover" id="incomes-table" style="display:none;">
    <thead class="table-dark">
        <tr>
            <th>Category</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for income in incomes %}
        <tr>
            <td>{{ income.category }}</td>
            <td>{{ income.name }}</td>
            <td>{{ "%.2f"|format(income.amount) }}</td>
            <td>
                <a href="{{ url_for('views.update_income', id=income.id) }}" class="btn btn-warning btn-sm">Update</a>
                <form action="{{ url_for('views.delete_income', id=income.id) }}" method="POST" style="display:inline;">
                    <button type="submit" class="btn btn-danger btn-sm"
                        onclick="return confirm('Are you sure you want to delete this income?')">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
<script>
    function showTable(tableId) {
        var expensesTable = document.getElementById('expenses-table');
        var incomesTable = document.getElementById('incomes-table');

        if (tableId === 'expenses') {
            changeToExpense();
            expensesTable.style.display = 'table';
            incomesTable.style.display = 'none';
        } else if (tableId === 'incomes') {
            changeToIncome();
            incomesTable.style.display = 'table';
            expensesTable.style.display = 'none';
        }
    }

    function changeToIncome() {
        // Change the header title
        document.getElementById("title-header").innerHTML = "Income - <span class='text-success' id='total-value'>₱{{total_income}}</span>";
    }

    function changeToExpense() {
        // Change the header title back to Expenses
        document.getElementById("title-header").innerHTML = "Expenses - <span class='text-danger' id='total-value'>₱{{total_expense}}</span>";
    }

    function filterExpensesByDate() {
        var selectedDate = document.getElementById('date-filter').value;
        var rows = document.querySelectorAll('#expenses-tbody tr');

        rows.forEach(function (row) {
            var rowDate = row.getAttribute('data-date').split('T')[0];
            if (selectedDate === '' || rowDate === selectedDate) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    }

    function filterExpensesByDate() {
        var selectedDate = document.getElementById("date-filter").value; // Get selected date
        var rows = document.querySelectorAll("tbody tr[data-date]"); // Select all rows with data-date attribute

        rows.forEach(row => {
            var rowDate = row.getAttribute("data-date"); // Get row's date

            // If no date is selected, show all rows. Otherwise, show only matching rows.
            if (selectedDate === "" || rowDate === selectedDate) {
                row.style.display = ""; // Show row
            } else {
                row.style.display = "none"; // Hide row
            }
        });
    }

</script>
{% endblock %}

website/templates/sign_up.html
{% extends "index.html" %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<form method="POST">
    <h3 class="text-center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email address">
    </div>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
    </div>
    <div class="form-group">
        <label for="password1">Confirm Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Confirm your password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}